number_of_rows:
  description: Number of grid rows
  value:
    type: int
    default: 10
    range:
      min: 3
      max: 10000
    units: '-'
number_of_columns:
  description: Number of grid columns
  value:
    type: int
    default: 10
    range:
      min: 3
      max: 10000
    units: '-'
grid_size_x:
  description: Grid size in x-direction
  value:
    type: float
    default: 1.0
    range:
      min: 0.01
      max: 1000000
    units: m
grid_size_y:
  description: Grid size in y-direction
  value:
    type: float
    default: 1.0
    range:
      min: 0.01
      max: 1000000
    units: m
elevation_profile:
    description: Elevation profile of rectangular domain
    value:
        type: choice
        default: 'shallow linear ramp'
        choices:
        - 'shallow linear ramp'
        - 'steep linear ramp'
        - 'tall step down'
        - 'short step down'
        - 'step up'
        - 'dam'
        - 'thin cylinder'
        - 'thick cylinder'
        - 'wing dams'
        - 'alternating dykes'
output_filename:
    description: Name of ANUGA output file (.sww)
    value:
        type: string
        default: 'anuga_output'
        units: '-'
output_timestep:
  description: Timestep for saving output to SWW file
  value:
    type: int
    default: 10
    range:
      min: 1
      max: 20000
    units: s
dict_of_boundary_conditions:
  description: Dictionary of boundary tags and boundary conditions
  value:
    type: string
    default: "{'left': ['Dirichlet', 0.4, 0, 0],'right': 'Reflective','top': 'Reflective','bottom': 'Reflective'}"
    units: '-'
initial_flow_depth:
  description: Initial water depth across the domain
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 50.0
    units: m
use_sed_transport_operator:
    description: Option to use the suspended sediment transport operator
    value:
        type: choice
        default: 'False'
        choices:
        - 'True'
        - 'False'
inflow_sediment_concentration:
  description: Volumetric concentration of suspended sediment at inflow boundary
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 0.3
    units: '-'
initial_sediment_concentration:
  description: Volumetric concentration of suspended sediment for all flow at start of simulation
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 0.3
    units: '-'
use_vegetation_operator:
    description: Option to use the vegetation drag operator
    value:
        type: choice
        default: 'False'
        choices:
        - 'True'
        - 'False'
stem_diameter:
  description: Diameter of vegetation stems throughout the model domain
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 1.0
    units: m
stem_spacing:
  description: Spacing of vegetation stems throughout the model domain
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 10.0
    units: m
friction_parameter:
  description: Manning n friction coefficient
  value:
    type: float
    default: 0.0
    range:
      min: 0.0
      max: 1.0
    units: '-'



